version: "3.9"
services:
  redis:
    container_name: redis-server
    image: "hub.hamdocker.ir/redis:alpine" # pull through cache of hamravesh.ir
    network_mode: "host"
    volumes:
      - redis:/data
  web:
    container_name: url-shortener
    build: .
    network_mode: "host"
    depends_on: ["redis"]
    volumes:
      - shortener:/cold-urls.db
volumes:
  redis:
  shortener: